# Generated by Django 4.0.6 on 2022-10-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_created_at_order_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='paymentMethod',
        ),
    ]
